# Generated by Django 4.1.2 on 2023-01-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gymapp1", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="gym", old_name="name", new_name="uname",),
    ]
